# Urbania API — Bootstrap Setup Script
# Run from: code/api/
# PowerShell execution: .\SETUP.ps1

Write-Host "=== Urbania API Bootstrap (API_BOOTSTRAP-B01) ===" -ForegroundColor Cyan
Write-Host ""

# Step 0: Verify prerequisites
Write-Host "[0/7] Verifying prerequisites..." -ForegroundColor Yellow
php --version 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: PHP not found. Install PHP 8.5 with openssl extension." -ForegroundColor Red
    exit 1
}

composer --version 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Composer not found. Install Composer 2.x." -ForegroundColor Red
    exit 1
}

docker compose version 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker Compose not found." -ForegroundColor Red
    exit 1
}

Write-Host "✓ Prerequisites OK" -ForegroundColor Green
Write-Host ""

# Step 1: Install dependencies
Write-Host "[1/7] Installing Composer dependencies..." -ForegroundColor Yellow
composer install
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: composer install failed." -ForegroundColor Red
    exit 1
}
Write-Host "✓ Dependencies installed (JWT keys generated by post-install hook)" -ForegroundColor Green
Write-Host ""

# Step 2: Generate APP_KEY
Write-Host "[2/7] Generating APP_KEY..." -ForegroundColor Yellow
php artisan key:generate
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: key:generate failed." -ForegroundColor Red
    exit 1
}
Write-Host "✓ APP_KEY generated" -ForegroundColor Green
Write-Host ""

# Step 3: Initialize git repo
Write-Host "[3/7] Initializing git repository..." -ForegroundColor Yellow
git init
git add -A
git commit -m "feat: esqueleto inicial del proyecto Laravel (API_BOOTSTRAP-B01)

- Laravel 13 + PHP 8.5
- PostgreSQL 5434 / Redis 6379 / nginx 8081 / Mailpit 1025:8025
- Estructura DDD: src/Shared/ con autoload PSR-4
- JWT RS256 (firebase/php-jwt + generador de llaves)
- Pest, PHPStan nivel 10, Pint
- routes/dev.php cargado solo en local/testing
- Scripts composer: test, stan, lint, fmt, ci, docker-*"
if ($LASTEXITCODE -ne 0) {
    Write-Host "WARNING: git commit may have failed (check if git is configured)." -ForegroundColor Yellow
}
Write-Host "✓ Git repo initialized" -ForegroundColor Green
Write-Host ""

# Step 4: Start Docker services
Write-Host "[4/7] Starting Docker services..." -ForegroundColor Yellow
docker compose up -d
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: docker compose up failed. Check Docker is running." -ForegroundColor Red
    exit 1
}
Write-Host "✓ Docker services starting..." -ForegroundColor Green
Write-Host ""

# Step 5: Wait for PostgreSQL to be ready and create test database
Write-Host "[5/7] Waiting for PostgreSQL and creating test database..." -ForegroundColor Yellow
Start-Sleep -Seconds 5
docker compose exec postgres createdb -U urbania urbania_test 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "NOTE: urbania_test may already exist — continuing." -ForegroundColor Yellow
}
Write-Host "✓ Test database ready" -ForegroundColor Green
Write-Host ""

# Step 5.5: Migrate and seed main database
Write-Host "[5.5/7] Migrating and seeding main database..." -ForegroundColor Yellow
Start-Sleep -Seconds 3
php artisan migrate --seed
if ($LASTEXITCODE -ne 0) {
    Write-Host "NOTE: migrate --seed failed, trying migrate:fresh --seed..." -ForegroundColor Yellow
    php artisan migrate:fresh --seed
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Database migration and seeding failed." -ForegroundColor Red
        exit 1
    }
}
Write-Host "✓ Main database migrated and seeded" -ForegroundColor Green
Write-Host ""

# Step 6: Run composer ci (lint + stan + test)
Write-Host "[6/7] Running composer ci (lint + stan + test)..." -ForegroundColor Yellow
composer ci
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: composer ci failed. Review output above." -ForegroundColor Red
    exit 1
}
Write-Host "✓ composer ci passed" -ForegroundColor Green
Write-Host ""

# Step 7: Show Docker status
Write-Host "[7/7] Docker services status:" -ForegroundColor Cyan
docker compose ps
Write-Host ""

Write-Host "=== Bootstrap complete! ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Mailpit UI: http://localhost:8025" -ForegroundColor Gray
Write-Host "nginx API:  http://localhost:8081" -ForegroundColor Gray
Write-Host ""
Write-Host "To verify /dev/* routes are not loaded in production:" -ForegroundColor Gray
Write-Host "  `$env:APP_ENV='production'; php artisan serve --port=9999" -ForegroundColor Gray
Write-Host "  curl http://localhost:9999/dev/any-route  # must return 404" -ForegroundColor Gray
